[package]
name = "celkit"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["std"]
std = [
  "celkit-core/std"
]

[dependencies]
celkit-core = { path = "../celkit_core/" }
